import { ReactComponent as CloseIcon } from '../../icons/close.svg';

import * as s from './AboutUs.styled';

const AboutUs = () => {
  return (
    <s.Container>
      <s.MainTitleContainer>
        <s.MainTitle>
          a Story that started with{' '}
          <s.Span>
            one simple <br /> ape
          </s.Span>
        </s.MainTitle>
      </s.MainTitleContainer>

      <s.MainDescriptionContainer>
        <s.MainDescription>
          WHO GOT <br /> FED UP WITH BORING <br /> AND HYPOCRITIC <br />
          COMMONPLACE THIS IS <br />
          HOW THE IDEA OF <br />
          ESCAPING AND DYNAMIC <br />
          JOURNEY ON THE YACHT
        </s.MainDescription>
      </s.MainDescriptionContainer>

      <s.SecondDescriptionContainer>
        <s.IconContainer>
          <CloseIcon />
        </s.IconContainer>

        <s.SecondDescription>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </s.SecondDescription>
      </s.SecondDescriptionContainer>
    </s.Container>
  );
};

export default AboutUs;
